name: News event preparation
description: Create a request for new event
title: "#XX %w{Jan Feb Mar Apr Jun Jul Aug Sep Nov Dec} Talk and socialize"
labels: [Talk]
assignees: []
body:
  - type: textarea
    id: link
    attributes:
      placeholder: Exact event url can be found https://www.meetup.com/Elixir-Berlin/events/
      value: |
        Event URL: <TODO: https://www.meetup.com/Elixir-Berlin/events/gdsglryccnbsb/>

  - type: textarea
    id: time
    attributes:
      placeholder: Date and time of the planned event
      value: |
        Time: <TODO: eg. 14th October 7pm CEST>

  - type: textarea
    id: location
    attributes:
      value: |
        - [ ] "Location: Remote/Hosting comapny"

  - type: textarea
    id: talks
    attributes:
      label: Talks
      value: |
        - [ ] <talk name to be added>
        - [ ] <talk name to be added>
